name: Publish to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  main:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Python
        uses: actions/setup-python@v5
        with:
          python-version: "*"

      - name: Install latest pip and build
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build
      - name: Build source distribution & pure wheel
        run: python -m build

      - name: Upload sdist as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/

  upload_all:
    name: Upload to PyPI
    needs: [main]  # cibuildwheel
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Upload to PyPI via Twine
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
